services:
  frontend:
    image: ghcr.io/profiidev/images/node-alpine-dev:main
    pull_policy: always
    volumes:
      - .:/app
    tty: true
    networks:
      - proxy
    ports:
      - '5174:5174'
    # command: npm install
    command: npm run dev -- --host
    working_dir: /app/frontend

  backend:
    image: ghcr.io/profiidev/images/rust-musl-watch:main
    pull_policy: always
    volumes:
      - .:/app
      - ./backend/data:/data
    networks:
      - proxy
    ports:
      - '9000:9000'
      - '5173:8000'
    tty: true
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run', '-C', 'backend']
    environment:
      - RUST_LIB_BACKTRACE=0

networks:
  proxy:
