name: Auto Merge PR with Components Update

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    if: ${{ github.event.label.name == 'components-update' && github.event.pull_request.user.login == 'Profiidev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Enable auto-merge for PR
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}