[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.223", features = ["derive"] }
sea-orm = { version = "1.1.16", features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
] }

[lib]
name = "entity"
path = "src/lib.rs"
